name = "MarkovitzDeFi"
uuid = "218bb638-b20d-46b4-b362-ab50618ca53b"
authors = ["Louis Latournerie"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Distributions = "0.25.118"
LinearAlgebra = "1.11.0"
julia = "1.9.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
